### PR TITLE
Formatting to markdown standard, update readme, setup python

### PR DESCRIPTION
**Pull request by curiosdevcookie**
- **Conforming md files to markdown standard.**
- **Add TOC to readme to improve navigation within repo.**
- **Add python setup.**

### CODE REVIEW

**Comment by inspired-cemonds** [comment]
Overall looks good, thanks.
I currently don't see what would happen if this is merged. Would it be merged as a single commit/squashed? If yes, I'm wondering if we shouldn't split the python setup from the formatting of the documentation.

**Comment by inspired-cemonds** [comment]
> Overall looks good, thanks. I currently don't see what would happen if this is merged. Would it be merged as a single commit/squashed? If yes, I'm wondering if we shouldn't split the python setup from the formatting of the documentation.

Ahhh, nevermind, I just saw the different options in Merge. So what merge strategy are you going to use?

**Comment by curiosdevcookie** [comment]
> Overall looks good, thanks. I currently don't see what would happen if this is merged. Would it be merged as a single commit/squashed? If yes, I'm wondering if we shouldn't split the python setup from the formatting of the documentation.

image

**Comment by curiosdevcookie** [comment]
> > Overall looks good, thanks. I currently don't see what would happen if this is merged. Would it be merged as a single commit/squashed? If yes, I'm wondering if we shouldn't split the python setup from the formatting of the documentation.
> 
> Ahhh, nevermind, I just saw the different options in Merge. So what merge strategy are you going to use?
Usually, I would have gone for a merge commit. But now, that I start to like/get to know rebasing, I'd try rebase and merge.

**Pull request merged**
